### ISSUE TITLE
Json Schema checkbox

### ISSUE THREAD

**Issue by ammarkhan967** [BlueBaseJS/plugin-json-schema-components#33]
Json Schema checkbox bug

## Description
Json Schema checkbox is having extra vertical padding which should be removed

## Expected Behavior

Json Schema checkbox is having extra vertical padding which should be removed

## Actual Behavior
Json Schema checkbox is having no vertical padding 

## Possible Fix
Possible fix will be in json schema checkbox

## Steps to Reproduce

1. User can reproduce this by just using checkbox of the json schema in form.

## Context
Json Schema checkbox is having extra vertical padding which should be removed

## Screenshots
Run a Form Component of Mevris (Required)

**Comment by danial24** [comment]
@artalat @ammarkhan967 

The issue is not about CheckBox getting extra space. Every component gets a padding of 16px in json forms.

So every component is wrapped into it. The same behavior is not being realised in case Radios as they are added in a single component of RadioGroup having the padding around them only once. 
If we are to use a checkbox component alone somewhere it is good but whenever there will be multiple checkboxes, we will need to create a component that can render multiple of these with one root padding.

**Comment by artalat** [comment]
can we meet and discuss please?
